<a href="https://colab.research.google.com/github/ishitha1611/Training/blob/main/TrainingDay12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(30,99,20)
a

array([85, 32, 67, 82, 89, 61, 59, 32, 33, 80, 78, 82, 79, 71, 62, 79, 33,
       54, 44, 88])

In [ ]:
b= np.random.randint(20,80,(8,9))
b

array([[71, 64, 48, 70, 22, 58, 67, 20, 49],
       [49, 79, 24, 27, 29, 61, 48, 64, 78],
       [28, 71, 54, 43, 52, 57, 42, 23, 63],
       [28, 32, 54, 39, 47, 24, 70, 74, 59],
       [20, 20, 31, 66, 49, 76, 78, 27, 46],
       [73, 46, 41, 60, 58, 72, 69, 64, 69],
       [36, 62, 63, 33, 70, 56, 58, 45, 23],
       [71, 50, 74, 29, 51, 53, 21, 43, 37]])

In [ ]:
b.shape

(8, 9)

In [ ]:
b.ndim

2

In [ ]:
b[7,0]

71

In [ ]:
b[2:6]

array([[28, 71, 54, 43, 52, 57, 42, 23, 63],
       [28, 32, 54, 39, 47, 24, 70, 74, 59],
       [20, 20, 31, 66, 49, 76, 78, 27, 46],
       [73, 46, 41, 60, 58, 72, 69, 64, 69]])

In [8]:
import pandas as pd

In [21]:
k = [[4,7],[2,9],[7,3],[90,50]]
k

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [22]:
t=np.array(k)
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [23]:
t.shape

(4, 2)

In [26]:
t.ndim

2

In [35]:
pd.Series(t)

ValueError: Data must be 1-dimensional, got ndarray of shape (4, 2) instead

In [36]:
pd.DataFrame(t)

0   1
0   4   7
1   2   9
2   7   3
3  90  50

In [43]:
df = pd.DataFrame(t,columns=['name','sub'],index=[289,290,291,292])
df

name  sub
289     4    7
290     2    9
291     7    3
292    90   50

In [44]:
df.columns

Index(['name', 'sub'], dtype='object')

In [45]:
df['sub']

289     7
290     9
291     3
292    50
Name: sub, dtype: int64

In [46]:
df['sub'].std()

21.975364995072702

In [47]:
df['sub'].min()

3

In [48]:
df['sub'].max()

50

In [50]:
df['sub'].quantile(0.25)

6.0

In [51]:
df['sub'].quantile(0.75)

19.25

In [52]:
df['sub'].var()

482.9166666666667

In [54]:
df['sub'].mean()

17.25

In [55]:
df['sub'].median()

8.0