<a href="https://colab.research.google.com/github/ishitha1611/Training/blob/main/TrainingDay10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
numpy   : array operations


In [ ]:
import numpy as np

In [ ]:
j = [6,7,8,3,1,1]
j

[6, 7, 8, 3, 1, 1]

In [ ]:
d=np.array(j)
d

array([6, 7, 8, 3, 1, 1])

In [ ]:
type(d)


numpy.ndarray

In [ ]:
j.shape

AttributeError: 'list' object has no attribute 'shape'

In [ ]:
d.ndim

1

In [ ]:
d.reshape

<function ndarray.reshape>

In [ ]:
s = [[2,5,8,6,3],[9,8,7,5,6],[6,5,7,9,3],[11,8,31,58,45]]

In [ ]:
s

[[2, 5, 8, 6, 3], [9, 8, 7, 5, 6], [6, 5, 7, 9, 3], [11, 8, 31, 58, 45]]

In [ ]:
arr1 = np.array(s)

In [ ]:
arr1

array([[ 2,  5,  8,  6,  3],
       [ 9,  8,  7,  5,  6],
       [ 6,  5,  7,  9,  3],
       [11,  8, 31, 58, 45]])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr1.shape

(4, 5)

In [ ]:
arr1.ndim

2

In [ ]:
arr1.reshape

<function ndarray.reshape>

In [ ]:
j = [5,87,23,46,23,45]
j

[5, 87, 23, 46, 23, 45]

In [23]:
import numpy as np

In [24]:
l = np.array([3,5,6,7,8])

In [25]:
np.mean(l)

5.8

In [26]:
np.median(l)

6.0

In [28]:
np.var(l)

2.96

In [29]:
np.std(l)

1.7204650534085253

In [30]:
np.max(l)

8

In [31]:
np.min(l)

3

In [34]:
np.quantile(l,0.25)

5.0

In [39]:
np.random.rand()

0.7475384302149735

In [43]:
np.random.rand(100)

array([0.53147264, 0.19246283, 0.557648  , 0.06102103, 0.20778243,
       0.56386196, 0.87485807, 0.15854184, 0.58399614, 0.62598149,
       0.45924377, 0.2644605 , 0.83825512, 0.55689797, 0.15379933,
       0.65304111, 0.12651889, 0.729003  , 0.61994016, 0.29691284,
       0.54562138, 0.8224971 , 0.58474007, 0.07243821, 0.91843322,
       0.86284042, 0.18287886, 0.94222201, 0.98420552, 0.66319058,
       0.1462185 , 0.57315177, 0.46745124, 0.44872294, 0.0132622 ,
       0.29063909, 0.06323861, 0.70677513, 0.8623821 , 0.31037003,
       0.27072596, 0.55136193, 0.34853125, 0.71371658, 0.80931517,
       0.35727841, 0.17963412, 0.51222501, 0.30256445, 0.48213536,
       0.48884615, 0.26691619, 0.27196565, 0.46246461, 0.23391056,
       0.12427482, 0.19205731, 0.67097167, 0.09001428, 0.99525486,
       0.94456929, 0.15930456, 0.1079321 , 0.00150551, 0.09535757,
       0.63654442, 0.60245066, 0.15589938, 0.40853264, 0.04346577,
       0.56610915, 0.19208204, 0.29736787, 0.11320212, 0.23416

In [44]:
l.shape

(5,)

In [46]:
l.size

5

In [47]:
l.ndim

1

In [48]:
np.random.randint(1,100)

75

In [49]:
np.random.randint(36,86,(5,5))

array([[62, 47, 62, 49, 79],
       [59, 54, 56, 59, 62],
       [46, 69, 81, 69, 69],
       [61, 60, 66, 72, 84],
       [51, 66, 75, 81, 75]])

In [ ]:
np..